function tau_R = CALCtau_R(in1,in2,in3,in4,in5)
%CALCtau_R
%    tau_R = CALCtau_R(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Jan-2025 13:45:06

F_s1 = in5(3,:);
F_s2 = in5(4,:);
alpha_dot = in2(1,:);
beta_dot = in2(2,:);
mu_v1 = in5(1,:);
mu_v2 = in5(2,:);
tau_R = [atan(alpha_dot.*2.0e+1).*(F_s1+mu_v1.*abs(alpha_dot)).*6.366197723675814e-1;atan(beta_dot.*2.0e+1).*(F_s2+mu_v2.*abs(beta_dot)).*6.366197723675814e-1];
end
