function G = GVector(in1,in2,in3,in4)
%GVector
%    G = GVector(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Jan-2025 13:45:06

alpha = in1(1,:);
beta = in1(2,:);
g = in2(5,:);
l1 = in2(1,:);
l2 = in2(2,:);
m1 = in2(3,:);
m2 = in2(4,:);
t2 = cos(alpha);
t3 = cos(beta);
t4 = sin(alpha);
t5 = sin(beta);
t6 = t4.*t5;
t7 = t2.*t3;
t8 = -t7;
t9 = t6+t8;
G = [-g.*m2.*(l1.*t2-(l2.*t9)./2.0)-(g.*l1.*m1.*t2)./2.0;(g.*l2.*m2.*t9)./2.0];
end
