function J_dot = J_dot_func(in1,in2,l1,l2)
%J_dot_func
%    J_dot = J_dot_func(IN1,IN2,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Jan-2025 15:32:50

alpha = in1(1,:);
alpha_dot = in2(1,:);
beta = in1(2,:);
beta_dot = in2(2,:);
t2 = cos(alpha);
t3 = cos(beta);
t4 = sin(alpha);
t5 = sin(beta);
t6 = t4.*t5;
t7 = t2.*t3;
t8 = t2.*t5;
t9 = t3.*t4;
t10 = -t7;
t11 = t8+t9;
t12 = t6+t10;
t13 = beta_dot.*l2.*t11;
t14 = beta_dot.*l2.*t12;
t15 = -t13;
J_dot = reshape([t14-alpha_dot.*(l1.*t2-l2.*t12),t15-alpha_dot.*(l1.*t4+l2.*t11),0.0,t14+alpha_dot.*l2.*t12,t15-alpha_dot.*l2.*t11,0.0],[3,2]);
end
