function J = Jfunc(in1,l1,l2)
%Jfunc
%    J = Jfunc(IN1,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    07-Jan-2025 15:32:09

alpha = in1(1,:);
beta = in1(2,:);
t2 = cos(alpha);
t3 = cos(beta);
t4 = sin(alpha);
t5 = sin(beta);
t6 = t4.*t5;
t7 = t2.*t3;
t8 = t2.*t5;
t9 = t3.*t4;
t10 = -t7;
t11 = t8+t9;
t12 = l2.*t11;
t13 = t6+t10;
t14 = l2.*t13;
t15 = -t12;
t16 = -t14;
J = reshape([t15-l1.*t4,t16+l1.*t2,0.0,t15,t16,0.0],[3,2]);
end
