function M = M(in1,in2,in3)
%M
%    M = M(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    06-Jan-2025 22:32:24

I1 = in2(5,:);
I2 = in2(6,:);
alpha = in1(1,:);
beta = in1(2,:);
l1 = in2(1,:);
l2 = in2(2,:);
m1 = in2(3,:);
m2 = in2(4,:);
t2 = cos(alpha);
t3 = cos(beta);
t4 = sin(alpha);
t5 = sin(beta);
t6 = l1.^2;
t7 = l2.^2;
t8 = t2.^2;
t9 = t4.^2;
t10 = l1.*t2;
t11 = alpha.*t5;
t12 = l1.*t4;
t13 = t4.*t5;
t14 = t2.*t3;
t15 = t2.*t5;
t16 = t3.*t4;
t18 = -t14;
t19 = t11-1.0;
t20 = t15+t16;
t21 = t13+t18;
t22 = t3.*t20;
t23 = t5.*t20;
t25 = (l2.*t20)./2.0;
t32 = t19.*t20;
t24 = alpha.*t22;
t26 = t3.*t21;
t27 = t5.*t21;
t30 = (l2.*t21)./2.0;
t33 = t12+t25;
t34 = t19.*t21;
t28 = alpha.*t26;
t31 = -t27;
t36 = t23+t26;
t39 = m2.*t25.*t33;
t42 = l2.*m2.*t21.*(t10-t30).*(-1.0./2.0);
t50 = -I2.*t21.*(t24-t34);
t37 = t22+t31;
t38 = t28+t32;
t41 = I2.*t20.*t36;
t44 = I2.*t21.*t36;
t43 = I2.*t20.*t37;
t45 = I2.*t21.*t37;
t47 = I2.*t20.*t38;
t49 = I2.*t21.*t38;
t46 = -t45;
t52 = t43+t44;
t54 = t47+t50;
t53 = t41+t46;
M = reshape([I1.*t8+I1.*t9+t3.*t52+t5.*t53+m2.*t33.^2+m2.*(t10-t30).^2+(m1.*t6.*t8)./4.0+(m1.*t6.*t9)./4.0,t39+t42-t3.*t54+t5.*(t49+I2.*t20.*(t24-t34)),t39+t42-t19.*t52+alpha.*t3.*t53,t19.*t54+(m2.*t7.*t20.^2)./4.0+(m2.*t7.*t21.^2)./4.0+alpha.*t3.*(t49+I2.*t20.*(t24-t34))],[2,2]);
end
